# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171018_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/img.jpg', upload_to='avatar/'),
        ),
    ]
