# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 02:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171020_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, error_messages={'phone_err': '手机号码格式有误'}, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='phone_err', message='手机号码格式有误', regex='1[3578][0-9]{9}')]),
        ),
    ]
