# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171017_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(default='python', to='blog.Tag'),
        ),
    ]
